
# H2 Database
spring:
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: true
  datasource:
    url: "${DB_URL}"
    driver-class-name: "${DB_DRIVER_CLASSNAME}"
    username: "${DB_USERNAME}"
    password:  "${DB_PASSWORD}"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: "${REDIS_HOST}"
      port: ${REDIS_PORT}


jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}
